=== OlegKuts/EpamProjects/EpamProject3/files/banks.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://bankinfo.com/banks"
    xmlns:tns = "http://bankinfo.com/banks" elementFormDefault="qualified">
   <element name="banks">
    <complexType>
        <sequence>
            <element name="bank" type="tns:Bank" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
   </element>  
    <complexType name="Bank">
        <sequence>
            <element name="name" type="string"/>
            <element name="country" type="string"/>
            <element name="deposit" type="tns:Deposit"/>
        </sequence>
    </complexType>
    <complexType name="Deposit">
        <sequence>
            <element name="depositor" type="string"/>
            <element name="amount">
                <simpleType>
                    <restriction base="float">
                        <minInclusive value="100"/>
                        <pattern value="(\d)+(\.(\d){1,2})?"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="profitability">
                <simpleType>
                    <restriction base="float">
                        <minInclusive value="1"/>
                        <maxInclusive value="100"/>
                        <pattern value="(\d)+(\.)(\d){1,2}"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="constraints">
                <simpleType>
                    <restriction base="duration">
                        <minInclusive value="P1M"/>
                        <pattern value="(P){1}(\dY)?(\d\d?M)?"/>
                    </restriction>
                </simpleType>
            </element>         
        </sequence>
        <attribute name="type" use="required">
            <simpleType>
                <restriction base="string">
                    <enumeration value="demand deposit"/>
                    <enumeration value="savings deposit"/>
                    <enumeration value="term deposit"/>
                    <enumeration value="money market deposit"/>
                    <enumeration value="call deposit"/>
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="accountId" use="required">
            <simpleType>
                <restriction base="ID"/>
            </simpleType>
        </attribute>
    </complexType>
</schema>

=== OlegKuts/EpamProjects/EpamProject3/files/banks.xml
<?xml version="1.0" encoding="UTF-8"?>
<banks xmlns="http://bankinfo.com/banks"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://bankinfo.com/banks banks.xsd">
    <bank>
        <name>HKB Bank</name>
        <country>Bavaria</country>
        <deposit type="demand deposit" accountId="d172061">
            <depositor>Alissa Lange</depositor>
            <amount>5000</amount>
            <profitability>7.0</profitability>
            <constraints>P10M</constraints>
        </deposit>
    </bank>
    <bank>
        <name>Stadtsparkasse Hameln</name>
        <country>Germany</country>
        <deposit type="savings deposit" accountId="d69449">
            <depositor>Luca Freud</depositor>
            <amount>12000</amount>
            <profitability>5.0</profitability>
            <constraints>P2Y</constraints>
        </deposit>
    </bank>
    <bank>
        <name>Sparkasse Soest</name>
        <country>Austria</country>
        <deposit type="term deposit" accountId="d14413">
            <depositor>Vivian Sieghart</depositor>
            <amount>2000</amount>
            <profitability>4.5</profitability>
            <constraints>P1Y6M</constraints>
        </deposit>
    </bank>
</banks>
